{
 "title": "Module Content Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "program",
    "query": "SELECT DISTINCT program FROM program_content_competencies ORDER BY program"
   },
   {
    "name": "department",
    "query": "SELECT DISTINCT department FROM department_content_competencies ORDER BY department"
   },
   {
    "name": "module",
    "query": "SELECT\n  name_de || ' (' || code || ')' AS __text,\n  code AS __value\nFROM modules\nORDER BY code;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Module Content Competencies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  module_content_competencies\r\nWHERE\r\n  code IN ($module)\r\nORDER BY\r\n  value DESC;\r\n"
    }
   ]
  },
  {
   "title": "Module Content Requirements",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  module_content_requirements\r\nWHERE\r\n  code IN ($module)\r\nORDER BY\r\n  value DESC;\r\n"
    }
   ]
  },
  {
   "title": "Module Content Short Description",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  module_content_short_description\r\nWHERE\r\n  code IN ($module)\r\nORDER BY\r\n  value DESC;\r\n"
    }
   ]
  },
  {
   "title": "Module Content Content",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  module_content_content\r\nWHERE\r\n  code IN ($module)\r\nORDER BY\r\n  value DESC;\r\n"
    }
   ]
  },
  {
   "title": "Module Content ECTS",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  code,\r\n  ects AS label\r\nFROM\r\n  module_contents\r\nWHERE\r\n  code IN ($module);"
    }
   ]
  },
  {
   "title": "Module Content Responsibility",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  code,\r\n  responsibility AS label\r\nFROM\r\n module_content_responsibility\r\nWHERE\r\n  code IN ($module);\r\n"
    }
   ]
  },
  {
   "title": "Program Content Competencies",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  program_content_competencies\r\nWHERE\r\n  program IN ($program)\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Program Content Short Description",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  program_content_short_description\r\nWHERE\r\n  program IN ($program)\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Department Content Competencies",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  key_de AS label,\r\n  value\r\nFROM\r\n  department_content_competencies\r\nWHERE\r\n  department IN ($department)\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "modules",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  code,\r\n name_de,\n competencies_de,\r\n  short_description_de,\r\n  requirements_de,\r\n  content_de,\r\n  ects,\r\n  responsibility_de\r\nFROM\r\n  modules\r\nWHERE\r\n  code IN ($module);"
    }
   ]
  }
 ]
}