FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Default profile = local
ENV SPRING_PROFILES_ACTIVE=local

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
